### ISSUE TITLE
Missing minikerberos.pkinit

### ISSUE THREAD

**Issue by Zamanry** [dirkjanm/PKINITtools#6]
Python version: Python 3.9
OS: Kali Linux 2021.XX
PKINIT Status: Worked with Rubeus

I encountered the error `from minikerberos.pkinit import PKINIT` missing. I had installed `oscrypto` and `minikerberos` and also did `python -m pip install -r requirements.txt` to no avail. I tried sudo and no sudo adaptions also to no avail. In the end, I found that uninstalling minikerberos and installing from their [GitHub repository](https://github.com/skelsec/minikerberos) succeeded.

Adding this issue to note the workaround for future reference and closing due to likely pip being out-of-date.

**Comment by digitalohm** [comment]
Ressurecting this one

I'm getting a similar error:

```
/PKINITtools/gets4uticket.py", line 17, in <module>
    from minikerberos.common.url import KerberosClientURL, kerberos_url_help_epilog
ModuleNotFoundError: No module named 'minikerberos.common.url'
```

I've run `pip3 install impacket minikerberos` per the docs and `pip3 list` shows

```
minikerberos                   0.4.0
```

The command I'm attempting to execute is

```
┌──(venv)─(user@tehbox)-[~/PKINITtools]
└─$ KRB5CCNAME=out.ccache python3 gets4uticket.py kerberos+ccache://tehdomain.com\\tehdc\$:out.ccache@tehdc.tehdomain.com cifs/tehdc.tehdomain.com@tehdomain.com target-user@tehdomain.com targetuser.ccache -v
```

any ideas on solving this one?
